// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base_footer': string;
  'base_header': string;
  'content': string;
}
export const cssExports: CssExports;
export default cssExports;
