// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page': string;
  'table': string;
  'table_box': string;
}
export const cssExports: CssExports;
export default cssExports;
